name: aglitterr
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  lottie: ^1.3.0
  rflutter_alert: ^2.0.4
  youtube_player_flutter: ^8.0.0
  bottom_bar_with_sheet: ^2.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.2  
  firebase_auth: ^3.3.11  
  firebase_core: ^1.13.1
  loading_overlay: ^0.3.0
  google_sign_in: ^5.2.4
  flutter_facebook_auth: ^4.1.2
  cloud_firestore: ^3.1.11
  firebase_messaging: ^11.2.12
  animations: ^2.0.2
  intl: ^0.17.0
  circle_list: ^1.0.5
  sqflite: ^2.0.2
  open_file: ^3.2.1
  photo_view: ^0.13.0
  image_picker: ^0.8.5
  emoji_picker_flutter: ^1.1.2
  fluttertoast: ^8.0.9
  permission_handler: ^9.2.0
  file_picker: ^4.5.1
  pdf_viewer_plugin:
    git:
      url: https://github.com/boskokg/Pdf_Viewer_Plugin/
      ref: master
  google_maps_flutter: ^2.1.3
  geolocator: ^8.2.0
  just_audio: ^0.9.20
  percent_indicator: ^4.0.0
  record: ^3.0.4
  path_provider: ^2.0.9
  firebase_storage: ^10.2.12
  dio: ^4.0.6
  flutter_local_notifications: ^9.4.0
  http: ^0.13.4   
  maze: ^3.0.0   

  flutter_lints: ^1.0.0
  
flutter_icons:
  android: 'launcher_icon'
  ios: true
  image_path: 'assets/images/ds.jpg'  

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  uses-material-design: true

  assets:
    - assets/images/
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
